---
  - name: slaves_playbook
    hosts: slaves
    become_user: root
    tasks:
      - name: ensure docker is at the latest version
        yum:
          name: docker
          state: latest
      - name: ensure java is at the latest version
        yum:
          name: java-1.8.0-openjdk
          state: latest         
      - name: copying ca directory
        copy:
         src: ./ca
         dest: /
      - name: copying server directory
        copy:
         src: ./server
         dest: /
      - name: copying commands file
        copy:
         src: ./commands.sh
         dest: /
      - name: creating server keys and certificate
        command: /bin/bash /commands.sh server
      - name: configure the docker service
        lineinfile:
          path: /usr/lib/systemd/system/docker.service
          regexp: 'ExecStart'
          line: 'ExecStart=/usr/bin/dockerd -H tcp://192.168.56.105:4243 -H unix:///var/run/docker.sock --tlsverify --tlscacert=/home/tommy/Desktop/ca/ca.pem --tlscert=/home/tommy/Desktop/server/server-cert.pem --tlskey=/home/tommy/Desktop/server/server-key.pem'
          state: present
      - name: restart docker service
        service:
          name: docker
          state: restarted
      - name: delete useless files
        command: /bin/bash /commands.sh clean

      
         
        
